/*
 * Produces a single "desktop" jar from the official FTC SDK Android archives
 * (RobotCore, Hardware, FtcCommon, Vision) published on Maven Central, plus the
 * OpenCV / EasyOpenCV / AprilTag Java classes Vision depends on.
 *
 * The AARs' classes.jar files (plus the plain jars bundled inside RobotCore's
 * libs/ folder) are merged. Classes listed in shadowed-classes.txt are dropped
 * because FTCSim ships its own implementation of them.
 */
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import java.util.zip.ZipEntry

plugins { `java-library` }

java { withSourcesJar() }
tasks.withType<JavaCompile> { options.release.set(17); options.encoding = "UTF-8" }

val ftcSdkVersion: String = (rootProject.extra.properties["ftcSdkVersion"] as String?) ?: "11.0.0"

val sdkAar: Configuration by configurations.creating {
    isTransitive = false
}

// Vision's own dependencies (OpenCV Java bindings, EasyOpenCV, AprilTag). The Java classes are needed so
// team code that touches org.opencv / org.openftc types compiles; their native libraries are not loaded.
val visionDeps = mapOf(
    "org.openftc:easyopencv" to "1.7.3",
    "org.openftc:apriltag" to "2.1.0",
    "org.openftc:opencv-repackaged-bundled-dylibs" to "4.10.0-A",
)

dependencies {
    listOf("RobotCore", "Hardware", "FtcCommon", "Vision").forEach { name ->
        sdkAar("org.firstinspires.ftc:$name:$ftcSdkVersion") {
            artifact { type = "aar" }
        }
    }
    visionDeps.forEach { (ga, v) ->
        sdkAar("$ga:$v") { artifact { type = "aar" } }
    }
}

val desktopSdkJar by tasks.registering {
    group = "ftcsim"
    description = "Builds ftc-sdk-desktop-$ftcSdkVersion.jar from the FTC SDK AARs"
    val outFile = layout.buildDirectory.file("libs/ftc-sdk-desktop-$ftcSdkVersion.jar")
    val shadowFile = layout.projectDirectory.file("shadowed-classes.txt")
    inputs.files(sdkAar)
    inputs.file(shadowFile)
    outputs.file(outFile)
    doLast {
        val shadowPrefixes = shadowFile.asFile.readLines()
            .map { it.trim() }.filter { it.isNotEmpty() && !it.startsWith("#") }
            .map { it.replace('.', '/') }
        fun isShadowed(entryName: String): Boolean {
            if (!entryName.endsWith(".class")) return false
            val bin = entryName.removeSuffix(".class")
            return shadowPrefixes.any { bin == it || bin.startsWith("$it$") }
        }
        val out = outFile.get().asFile
        out.parentFile.mkdirs()
        val seen = HashSet<String>()
        var written = 0
        var stripped = 0
        ZipOutputStream(out.outputStream().buffered()).use { zos ->
            fun copyJar(jarBytes: ByteArray, label: String) {
                logger.debug("ftc-sdk: reading {}", label)
                val tmp = File.createTempFile("ftcsim-", ".jar")
                try {
                    tmp.writeBytes(jarBytes)
                    ZipFile(tmp).use { zf ->
                        for (e in zf.entries()) {
                            if (e.isDirectory) continue
                            val n = e.name
                            if (n.startsWith("META-INF/") && (n.endsWith(".SF") || n.endsWith(".RSA") || n.endsWith(".DSA") || n == "META-INF/MANIFEST.MF")) continue
                            if (isShadowed(n)) { stripped++; continue }
                            if (!seen.add(n)) continue
                            zos.putNextEntry(ZipEntry(n))
                            zf.getInputStream(e).use { it.copyTo(zos) }
                            zos.closeEntry()
                            written++
                        }
                    }
                } finally { tmp.delete() }
            }
            for (aar in sdkAar.files.sortedBy { it.name }) {
                logger.lifecycle("ftc-sdk: merging ${aar.name}")
                ZipFile(aar).use { zf ->
                    val classes = zf.getEntry("classes.jar") ?: error("No classes.jar in $aar")
                    copyJar(zf.getInputStream(classes).readBytes(), "${aar.name}!classes.jar")
                    for (e in zf.entries()) {
                        if (!e.isDirectory && e.name.startsWith("libs/") && e.name.endsWith(".jar")) {
                            logger.lifecycle("ftc-sdk:   + bundled ${e.name}")
                            copyJar(zf.getInputStream(e).readBytes(), "${aar.name}!${e.name}")
                        }
                    }
                }
            }
        }
        logger.lifecycle("ftc-sdk: wrote ${out.name} ($written entries, $stripped shadowed classes removed)")
    }
}

/**
 * Android resource classes. The AARs ship an R.txt (resource table) and res/values/values.xml but the
 * R classes themselves are generated by the Android build; SDK code such as DcMotorImpl.getDeviceName()
 * references R.string.* and resolves them through the Android Context. We generate the R classes (with
 * fresh ids) plus a table of the English string values so the compat Context can resolve them.
 */
val generateR by tasks.registering {
    group = "ftcsim"
    description = "Generates the SDK's R classes and resource string table from the AARs"
    val outDir = layout.buildDirectory.dir("generated/r")
    inputs.files(sdkAar)
    outputs.dir(outDir)
    doLast {
        val dir = outDir.get().asFile
        dir.deleteRecursively(); dir.mkdirs()
        val ids = LinkedHashMap<String, Int>()
        val strings = LinkedHashMap<Int, String>()
        var nextId = 0x7f010000
        fun idFor(type: String, name: String) = ids.getOrPut("$type/$name") { nextId++ }
        val stringRegex = Regex("<string name=\"([^\"]+)\"[^>]*>(.*?)</string>", RegexOption.DOT_MATCHES_ALL)
        for (aar in sdkAar.files.sortedBy { it.name }) {
            ZipFile(aar).use { zf ->
                val manifest = zf.getEntry("AndroidManifest.xml") ?: return@use
                val pkg = Regex("package=\"([^\"]+)\"").find(zf.getInputStream(manifest).reader().readText())?.groupValues?.get(1) ?: return@use
                val rtxt = zf.getEntry("R.txt") ?: return@use
                val byType = LinkedHashMap<String, MutableList<String>>()
                zf.getInputStream(rtxt).bufferedReader().forEachLine { line ->
                    val parts = line.trim().split(Regex("\\s+"), limit = 4)
                    if (parts.size < 4) return@forEachLine
                    val (jtype, rtype, name, value) = parts
                    val decl = when {
                        jtype == "int[]" -> "public static final int[] $name = $value;"
                        rtype == "styleable" -> "public static final int $name = ${value.toIntOrNull() ?: 0};"
                        else -> "public static final int $name = ${idFor(rtype, name)};"
                    }
                    byType.getOrPut(rtype) { mutableListOf() }.add(decl)
                }
                val pkgDir = File(dir, pkg.replace('.', '/')); pkgDir.mkdirs()
                File(pkgDir, "R.java").writeText(buildString {
                    append("package $pkg;\n\n/** Generated by FTCSim from ${aar.name}. */\npublic final class R {\n")
                    for ((t, decls) in byType) { append("    public static final class $t {\n"); decls.forEach { append("        $it\n") }; append("    }\n") }
                    append("}\n")
                })
                val values = zf.getEntry("res/values/values.xml")
                if (values != null) {
                    val xml = zf.getInputStream(values).reader().readText()
                    for (m in stringRegex.findAll(xml)) {
                        val id = ids["string/${m.groupValues[1]}"] ?: continue
                        var text = m.groupValues[2].trim()
                        text = text.replace("\\'", "'").replace("\\\"", "\"").replace("&lt;", "<").replace("&gt;", ">").replace("&amp;", "&").replace("&quot;", "\"")
                        if (text.startsWith("\"") && text.endsWith("\"") && text.length >= 2) text = text.substring(1, text.length - 1)
                        strings.putIfAbsent(id, text)
                    }
                }
            }
        }
        fun javaLiteral(s: String) = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "").replace("\t", "\\t") + "\""
        val genDir = File(dir, "ftcsim/generated"); genDir.mkdirs()
        File(genDir, "ResourceNames.java").writeText(buildString {
            append("package ftcsim.generated;\n\nimport java.util.HashMap;\nimport java.util.Map;\n\n/** Generated by FTCSim: resource ids to names and string values. */\npublic final class ResourceNames {\n")
            append("    private static final Map<Integer, String> NAMES = new HashMap<>();\n    private static final Map<Integer, String> STRINGS = new HashMap<>();\n")
            val nameEntries = ids.entries.toList()
            val chunks = nameEntries.chunked(800)
            chunks.forEachIndexed { i, chunk ->
                append("    private static void names$i() {\n")
                for ((k, v) in chunk) append("        NAMES.put($v, ${javaLiteral(k)});\n")
                append("    }\n")
            }
            val stringChunks = strings.entries.toList().chunked(400)
            stringChunks.forEachIndexed { i, chunk ->
                append("    private static void strings$i() {\n")
                for ((k, v) in chunk) append("        STRINGS.put($k, ${javaLiteral(v)});\n")
                append("    }\n")
            }
            append("    static {\n")
            chunks.indices.forEach { append("        names$it();\n") }
            stringChunks.indices.forEach { append("        strings$it();\n") }
            append("    }\n")
            append("    /** \"type/name\" of a resource id, or null. */\n    public static String name(int id) { return NAMES.get(id); }\n")
            append("    /** The English value of a string resource, else its name, else null. */\n    public static String string(int id) { String s = STRINGS.get(id); if (s != null) return s; String n = NAMES.get(id); return n == null ? null : n.substring(n.indexOf('/') + 1); }\n")
            append("}\n")
        })
        logger.lifecycle("ftc-sdk: generated R classes (${ids.size} resources, ${strings.size} strings)")
    }
}
sourceSets { main { java.srcDir(generateR) } }

// Consumable configuration so other modules can depend on the desktop jar.
val desktopSdk: Configuration by configurations.creating {
    isCanBeConsumed = true
    isCanBeResolved = false
}
artifacts {
    add("desktopSdk", desktopSdkJar.map { it.outputs.files.singleFile }) {
        builtBy(desktopSdkJar)
    }
}
tasks.named("assemble") { dependsOn(desktopSdkJar) }
